services:

  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

    # auto-pull models on startup
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull qwen3-coder:480b-cloud &&
      ollama pull nomic-embed-text:latest &&
      wait
      "

volumes:
  ollama_data: